### ISSUE TITLE
Matrix return complex double

### ISSUE THREAD

**Issue by NoPenguinsLand** [pierreablin/qndiag#14]
I'm using MATLAB version. The input variable is double, yet the output variable B is complex double. Is this normal?

**Comment by agramfort** [comment]
this happens with any input data for you?

**Comment by NoPenguinsLand** [comment]
Roughly 50% of the time. In my case, complex double arises when at least one of the eigenvalues of the covariance matrix is negative. However, according to Cholesky Factorization test, the mean covariance matrix and class-specific covariance matrices are already positive definite. So a very small negative eigenvalue sounds like a rounding issue to me.

**Comment by pierreablin** [comment]
Do you have a code snippet to reproduce this ?

**Comment by NoPenguinsLand** [comment]
I attached an example input variable C on [Google Drive] (https://drive.google.com/drive/folders/1sfkUWLdxgZT0fhb3JiWQrlbes7vyDQMk?usp=sharing). In qndiag.m, you will see a very small negative eigenvalue in the variable d in line 82, which eventually cause variable B to be complex (line 85).

**Comment by NoPenguinsLand** [comment]
Closing this, discussion continued in #15
